# Implement bradley-terry ranking system

In [29]:
import numpy as np

def bradley_terry(w, max_iter=1000, tol=1e-3):
    """https://en.wikipedia.org/wiki/Bradley%E2%80%93Terry_model"""
    p = np.ones(w.shape[0])
    for iteration in range(max_iter):
        p_old = p.copy()
        for i in range(w.shape[0]):
            p[i] = np.sum(w[i]*p/(p + p[i]))/np.sum(w[:, i]/(p + p[i]))
            #print(p_new[i], w[i]*p/(p + p[i]), w[:, i]/(p + p[i]))
        p /= p.prod()**(1/len(p))
        if np.linalg.norm(p - p_old) < tol:
            print(f"Converged after {iteration+1} iterations.")
            break
        print(p)
    return p

wins_matrix = [
    [0, 2, 0, 1],
    [3, 0, 5, 0],
    [0, 3, 0, 1],
    [4, 0, 3, 0]
]
wins_matrix = np.array(wins_matrix)
bradley_terry(wins_matrix, max_iter=1000).round(3)
# expected  [0.640, 1.043, 0.660, 2.270] as in wikipedia

[0.51637379 1.41260876 0.67160933 2.04125468]
[0.67734685 1.03368552 0.62447816 2.28708969]
[0.64996562 1.02624863 0.65621883 2.28459032]
[0.63867658 1.04248289 0.661457   2.27064091]
[0.63921261 1.04416265 0.66012747 2.26964904]
[0.63984841 1.04342369 0.65974738 2.27030673]
Converged after 7 iterations.


array([0.64 , 1.043, 0.66 , 2.27 ])